.github/workflows/build-haskell.yml, gen/haskell/README.md, gen/haskell/utxorpc.cabal
1. Fix paths in workflow files after moving to `gen/haskell`.
2. Add a Haskell-specific README to prevent warnings during packaging.
There was a cache miss causing the dependencies to be rebuilt from scratch. I think this is because the previous caches were from a workflow on a different branch causing a different [cache version](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key), but lets check when CI starts running on `main` that the cache is working properly.
=> Fix haskell build after move

.github/workflows/generate.yml, gen/rust/Cargo.toml
Update Rust plugins to latest versions.
The new plugins include breaking changes. Merging this PR may create breaking changes for the Rust crate. The Rust SDK will also require changes to its dependencies once it depends on code generated by this PR, but I have confirmed that it will build without any source code changes.
=> Update Rust plugins to latest

.github/actions/publish-haskell/action.yml
1. No artifact upload: caused by out-of-date artifact filepath.
2. Publish not running: caused by pattern matching on `ref/tags` instead of `refs/tags`.
=> Fix bugs in Haskell CI

gen/go/go.mod
This was triggering dependabot while the actual code downstream was using newer versions as updating is part of the CI workflow. Removing the versions here, entirely. This will appease dependabot.
=> fix(go): remove requirements as they are generated at build

gen/haskell/utxorpc.cabal, gen/rust/src/lib.rs, proto/utxorpc/v1alpha/query/query.proto
Rationale: the original name (given by me) was defined to convey the idea that this module could be used as backend provider for Tx builders (eg: lucid / mesh providers). The reality is that almost all of the requirements involving tx-building are actually data queries and the remaining requirements are already fulfilled by other modules (Submit, Watch).
=> refactor: rename Build module into Query

proto/utxorpc/v1alpha/cardano/cardano.proto, proto/utxorpc/v1alpha/query/query.proto
I'm proposing a new approach for defining queries where the pattern matching criteria is chain-specific instead of generic. This enables more expressive filters.
=> refactor(query): allow chain-specific queries

.github/actions/publish-haskell/action.yml, gen/docs/docs.md, gen/haskell/stack.yaml, gen/haskell/utxorpc.cabal
1. Minor modifications to Haskell package metadata.
2. Include Haddock (documentation) generation and publishing in the CI workflow.
3. Include changes to documentation markdown after running `buf generate proto`.
1. I'm not sure what the current process is regarding documentation, so I don't know if including these changes is appropriate. @wolf31o2 do you know?
=> fix: Improve haskell spec metadata and publish Haddocks in CI

proto/utxorpc/v1alpha/cardano/cardano.proto, proto/utxorpc/v1alpha/query/query.proto, proto/utxorpc/v1alpha/submit/submit.proto
This PR fills the gaps to allow U5C to work as a provider for tx-builder libraries such as Blaze and Lucid.
In particular, it adds:
- method to query datums by hash
- missing definition of cardano ledger pparams
- method to evaluate tx fees in submit module
The other required endpoints where already available.
=> feat: fill gaps to work as Blaze / Lucid provider

proto/utxorpc/v1alpha/sync/sync.proto
Previously, you could fetch *either* the raw bytes, *or* the chain, but not both; But they aren't mutually exclusive: it makes total sense to return *both* the native bytes and the interpreted structure according to some chain. This replaces `raw` with `native_bytes`
Comes out of a conversation with @scarmuega and @wolf31o2 on discord.
=> Modify AnyChainBlock to allow fetching native bytes

proto/utxorpc/v1alpha/cardano/cardano.proto
Add missing redeemer fields to required structs:
- multiasset
- certificate
- withdrawal
=> fix(cardano): add missing redeemer fields

.gitignore, gen/node/.gitignore, proto/utxorpc/v1alpha/cardano/cardano.proto, proto/utxorpc/v1alpha/query/query.proto
This PR adds `native_bytes` field into `PlutusData` cardano message
this is useful for stuff like **Transaction Builder** integrations where there is already a built CBOR (de)serializer.
=> feat(cardano): Add `native_bytes` field into `PlutusData`

proto/utxorpc/v1alpha/cardano/cardano.proto
This PR introduces `Datum` struct as the container for `PlutusData` in a `TxOutput`, this avoids having recursive `native_bytes` within `PlutusData` itself.
=> refactor: avoid recursive `native_bytes` for`PlutusData`

.github/workflows/publish-all.yml, gen/haskell/utxorpc.cabal
This PR solves CI haskell dependency issue and re-enables haskell workflow
=> chore: update proto-lens-runtime dependency to >= version 0.7.0.6

gen/haskell/stack.yaml, gen/haskell/stack.yaml.lock
This PR adds proto-lens-runtime dependency to stack.yaml to fix CI errors
=> ci(haskell): add proto-lens-runtime dependency to stack.yaml

.github/actions/publish-node/action.yml
This PR adds the `registry-url` parameter to the `actions/setup-node` step in our npm publish workflow.
```yaml
- name: Setup npm
uses: actions/setup-node@v4
with:
node-version: 20.11.0
cache: "npm"
cache-dependency-path: "codegen/node/package.json"
registry-url: 'https://registry.npmjs.org'
```
1. **Authentication Setup**: It configures npm to use the `NODE_AUTH_TOKEN` for the specified registry.
2. **Security**: Ensures the auth token is only used for the intended registry.
3. **GitHub Actions Requirement**: Unlike local environments, GitHub Actions needs this explicit configuration to properly authenticate npm operations.
Without `registry-url`, the workflow fails to authenticate, even with `NODE_AUTH_TOKEN` set, due to GitHub Actions' specific behavior.
=> ci(node): authentication publish workflow fix

proto/utxorpc/v1alpha/cardano/cardano.proto
This PR updates the submit module's TxEval result to return `Repeated Redeemer` instead of only `ExUnits`. This change enables transaction builders to gain a more fine-grained perspective of the evaluation process.
Additionally, it modifies the `Redeemer` structure to align more closely with the CDDL specification by adding the missing `Index` and `ExUnits` fields.
=> feat(submit): TxEval now returns Redeemers instead of ExUnits, Redeemer Include (Index and ExUnits)

proto/utxorpc/v1alpha/cardano/cardano.proto
This PR adds the `original_cbor` to the `Redeemer` message to allow tools to use (de)serializers and consume the redeemer directly.
This closes: #132
=> feat: add original_cbor field to Redeemer message

proto/utxorpc/v1alpha/query/query.proto, proto/utxorpc/v1alpha/watch/watch.proto
=> Include a block reference inside transaction watchers

proto/utxorpc/v1alpha/sync/sync.proto, proto/utxorpc/v1alpha/watch/watch.proto
=> More flexible block identifiers for requests

gen/docs/docs.md, proto/utxorpc/v1alpha/cardano/cardano.proto, proto/utxorpc/v1alpha/query/query.proto
This PR is an alternative to #147 that combines everything to a single endpoint with field masks instead
=> (feat) ReadChainConfig endpoint

proto/utxorpc/v1alpha/submit/submit.proto
It would be useful to have an error message in the response if the transaction submission has failed. This PR adds a `oneof` field with an error message instead of a transaction reference if there was an error.
=> feat(submit): add error messages to transaction submission result

proto/utxorpc/v1alpha/cardano/cardano.proto
JavaScript numbers. To be more specific, let's try to use a max value for unsigned integer `18446744073709551615` as a coin value:
```
% node                                        
Welcome to Node.js v22.19.0.
Type ".help" for more information.
> let coin = 18446744073709551615
undefined
> coin
18446744073709552000
```
You can observe a precision loss, because JavaScript uses floating point [IEEE-754](https://en.wikipedia.org/wiki/IEEE_754) standard for `Number` representation.
The `coin` field in proto definitions is represented as `uint64`, which gets translated to `Number` by `protoc-javascript`.
To work around this issue, one can use `jstype` protobuf field option, to encode the coin value as `string` in JavaScript which then can be safely converted to a proper `BigInt` type without …
=> fix(cardano): use `string` in JavaScript for cardano coin representation
